# Two-dimensional array

In [11]:
import numpy as np

In [12]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [17]:
sample_matrix[1,2]
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [16]:
sample_matrix[:,(3,2)]
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [18]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [20]:
sample_matrix[2]

array([56, 76, 24,  7])

### selection techiniques

In [22]:
sample_array=np.arange(1,25)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [24]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10])

In [25]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [26]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [27]:
np.max(sample_array)

24

In [28]:
np.min(sample_array)

1

In [29]:
np.argmax(sample_array)

23

In [30]:
np.argmin(sample_array)

0

In [32]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [33]:
np.mean(sample_array)

12.5

In [34]:
np.std(sample_array)

6.922186552431729

In [35]:
np.var(sample_array)

47.916666666666664

In [37]:
np.median(sample_array)

12.5

In [38]:
array=np.random.randn(3,4)

In [39]:
array

array([[-0.48264861, -0.80840971,  0.37236444,  0.84975504],
       [-0.73496798,  0.13809278, -0.65905514, -0.06749229],
       [-0.47481562, -0.16993103, -1.95777977,  0.67544047]])

In [41]:
np.round(array,decimals=2)

array([[-0.48, -0.81,  0.37,  0.85],
       [-0.73,  0.14, -0.66, -0.07],
       [-0.47, -0.17, -1.96,  0.68]])

In [44]:
sports=np.array(['golf','cricket','football','cricket'])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

# pandas dataframe and indexing

In [64]:
import pandas as pd
import numpy as np

In [65]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])

In [66]:
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [67]:
sports1['football']

2

In [68]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [69]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [71]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.237603  0.843813  0.068286  0.022634  0.893492
B  0.012242  0.760578  0.752146  0.501581  0.598871
C  0.692635  0.231141  0.467795  0.065043  0.630695
D  0.478692  0.522759  0.986609  0.608256  0.168435
E  0.904073  0.862673  0.969545  0.117305  0.991165
F  0.652180  0.488931  0.660465  0.750202  0.792155
G  0.950638  0.349229  0.034073  0.535135  0.389789
H  0.436191  0.873930  0.404736  0.795798  0.517710

In [72]:
df1["Score1"]

A    0.237603
B    0.012242
C    0.692635
D    0.478692
E    0.904073
F    0.652180
G    0.950638
H    0.436191
Name: Score1, dtype: float64

In [73]:
df1[["Score1","Score2"]]

Score1    Score2
A  0.237603  0.843813
B  0.012242  0.760578
C  0.692635  0.231141
D  0.478692  0.522759
E  0.904073  0.862673
F  0.652180  0.488931
G  0.950638  0.349229
H  0.436191  0.873930

In [75]:
df1["Score6"]=df1["Score1"]+df1["Score2"]
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.237603  0.843813  0.068286  0.022634  0.893492  1.081416
B  0.012242  0.760578  0.752146  0.501581  0.598871  0.772820
C  0.692635  0.231141  0.467795  0.065043  0.630695  0.923775
D  0.478692  0.522759  0.986609  0.608256  0.168435  1.001451
E  0.904073  0.862673  0.969545  0.117305  0.991165  1.766746
F  0.652180  0.488931  0.660465  0.750202  0.792155  1.141111
G  0.950638  0.349229  0.034073  0.535135  0.389789  1.299867
H  0.436191  0.873930  0.404736  0.795798  0.517710  1.310121

In [79]:
df2={'ID':['201','202','203','204'],'Name':['sriram','maha','cherry','siri'],'Profit':[24,13,1,11]}
df=pd.DataFrame(df2)
df

ID    Name  Profit
0  201  sriram      24
1  202    maha      13
2  203  cherry       1
3  204    siri      11

In [80]:
df["ID"]

0    201
1    202
2    203
3    204
Name: ID, dtype: object

In [81]:
df[["ID","Name"]]

ID    Name
0  201  sriram
1  202    maha
2  203  cherry
3  204    siri

In [82]:
df=df.drop("ID",axis=1)

In [83]:
df

Name  Profit
0  sriram      24
1    maha      13
2  cherry       1
3    siri      11

In [84]:
df.drop(3)

Name  Profit
0  sriram      24
1    maha      13
2  cherry       1